[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
optimism-goerli = "${OPTIMISM_GOERLI_RPC_URL}"
aribtrum-goerli = "${ARBITRUM_GOERLI_RPC_URL}"
base-goerli = "${BASE_GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
optimism-goerli = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
aribtrum-goerli = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
base-goerli = { key = "${BASE_ETHERSCAN_API_KEY}" }
