name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-C link-args=-Wl,--allow-multiple-definition"
          ACTIVATION_BLOCK: 3804028
          PARA_ID: 1000
          RELAY_WS_URL: "wss://rococo-rpc.polkadot.io:443"
          PARA_WS_URL: "wss://rococo-asset-hub-rpc.polkadot.io:443"
        with:
          command: test
          toolchain: stable
          args: --release --locked --manifest-path ./forge/Cargo.toml -- --nocapture

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          toolchain: nightly
          args: --manifest-path ./forge/Cargo.toml --all -- --check
