name: Build & Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

env:
    FOUNDRY_PROFILE: ci

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  submodules: recursive
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Run Forge build
              run: |
                  yarn
                  forge --version
                  forge build --sizes
              id: build
